### ISSUE TITLE
error when run tecogan.bat (no detect tensorflow)

### ISSUE THREAD

**Issue by aakh1361** [Sanaxen/tecoGAN_app#8]
I install tensorflow and tensorflow-gpu
when run this code in anaconda and python show me specifications my cpu and gpu
```
from tensorflow.python.client import device_lib
print( device_lib.list_local_devices())
```
```
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17329821801997483339
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 2262853222
locality {
  bus_id: 1
  links {
  }
}
incarnation: 1372736402601005389
physical_device_desc: "device: 0, name: GeForce GTX 780 Ti, pci bus id: 0000:01:00.0, compute capability: 3.5"
]
```

But when Run tecogan.bat don't dectect my tensorflow and show me Error Down
i used v0.1.1d
```
C:\dist\main>cd tecoGAN

C:\dist\main\tecoGAN>del /Q ./results/LR/calendar/*.png
Invalid switch - "results".

C:\dist\main\tecoGAN>python main.py --cudaID 0 --output_dir ./results/ --summary_dir ./results/log/ --mode inference --i
nput_dir_LR ./LR/calendar --output_pre calendar  --num_resblock 16  --checkpoint ./model/TecoGAN --output_ext png
Traceback (most recent call last):
  File "C:\dist\main\env\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\dist\main\env\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\dist\main\env\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_impor
t_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\dist\main\env\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\dist\main\env\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import tensorflow as tf
  File "C:\dist\main\env\lib\site-packages\tensorflow\__init__.py", line 102, in <module>
    from tensorflow_core import *
  File "C:\dist\main\env\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\dist\main\env\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\dist\main\env\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\dist\main\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\dist\main\env\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\dist\main\env\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\dist\main\env\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\dist\main\env\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\dist\main\env\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_impor
t_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\dist\main\env\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\dist\main\env\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by Sanaxen** [comment]
Isn't the following helpful?
https://github.com/tensorflow/tensorflow/issues/40459

**Comment by Sanaxen** [comment]
**dist / main / copy_cuda.bat**
Please try it in advance.

However, **super_resolution_Application.exe**
Are you running from?
If not
**dist \ main \ tecoGAN \ LR \ calendar**
Requires 5 or more images.

**Comment by aakh1361** [comment]
@Sanaxen 
thank you for answer
I do run copy_cuda.bat
and copy some files
and afther super_resolution_Application.exe
but don't diffrent and show me same error up
